### ISSUE TITLE
Unable to find the API Links

### ISSUE THREAD

**Issue by Jayasoruban** [TufayelLUS/LinkedIn-Lead-Scraper#4]
Hello Sir, I'm unable find the API link that you have given in the code, I could find a similar API link after logging into LINKEDIN inside the Networks tab from inspect elements. But when I use that link in python its throwing me a error.

Please let me know where to find these two API Links it would be of great help to me.
api_link = 'https://www.linkedin.com/voyager/api/organization/companies?decorationId=com.linkedin.voyager.deco.organization.web.WebCompanyStockQuote-2&q=universalName&universalName={}'.format(quote(company_username))
resp = self.s.get(api_link, headers=headers).json()

resp = self.s.get('https://www.linkedin.com/voyager/api/search/blended?count=10&filters=List(currentCompany-%3E{},resultType-%3EPEOPLE)&origin=COMPANY_PAGE_CANNED_SEARCH&q=all&queryContext=List(spellCorrectionEnabled-%3Etrue)&start={}'.format(company_id,(int(page_no)-1) * 10), headers=headers).json()

**Comment by Jayasoruban** [comment]
Please tell me where to locate or find this API, I would really Appreciate it

**Comment by TufayelLUS** [comment]
Hi, I am no longer maintaining the code since it's been over a year already since I wrote the code and LinkedIn is a running platform that updates regularly. Therefore, it is common to have the API changed to something else and the old code is failed to work. You can use network logging software like Fiddler or browser network tab otherwise to explore their current API endpoints and change the request accordingly. I am pretty busy with my professional works and not getting spare time to look at the open-source projects at this moment.
